version: '4.4'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  ngrok:
    image: ngrok/ngrok:alpine
    command: http web:8080
    depends_on:
      - web
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
  web:
    build:
      context: .
      target: dev
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
